### ISSUE TITLE
Widget Tracking Issue

### ISSUE THREAD

**Issue by ellieeet123** [benbusby/whoogle-search#961]
This is mostly used to track the process of (hopefully) implementing all of Google's widgets that appear when searching certain keywords. I like this idea quite a lot and will likely be the one to implement the bulk of them, however if you see one you want to take a stab at, go ahead! Also, I was not able to find a complete list of all the widgets that can appear, so if there are any I missed feel free to let me know. 

## Tools

- [ ] Calculator
- [ ] Color Picker
- [ ] Timer/Stopwatch
- [ ] RNG tools, e.g. dice, coin flip, spinner, classic RNG, etc
- [ ] Tuner
- [ ] Metronome
- [ ] Meditation 
- [ ] Weather
- [ ] Stock/Cryptocurrency quotes
- [ ] Unit Conversion

## Games (lower priority)

- [ ] Snake
- [ ] Minesweeper
- [ ] Solitaire
- [ ] Pac Man
- [ ] Tic Tac Toe
- [ ] Memory Game

**Comment by cazwacki** [comment]
@ellieeet123 I love this initiative. I would love to eventually join you in taking on some of these tool implementations. I myself would love to be able to reimplement Google's restaurant browsing functionality, as it's something my friends and family regularly use.

@benbusby to what extent do you want these features in whoogle-search? I see in #1012 you are hesitant about having some plugins encoded directly into whoogle-search. This could be a use case for GitHub organization for whoogle-search and separating dedicated plugins into their own respective repositories. It would spread ownership as well, so you would not need to be the sole maintainer (esp. for plugin code).

**Comment by benbusby** [comment]
@cazwacki I'm not sure if I want these types of plugins at all, even if they were in separate repos. I was fine with the calculator since a surprising number of people wanted that functionality, but the majority -- if not all -- of these have already been implemented elsewhere as browser extensions or apps, and I don't see the point of reimplementing these for search. 

Ultimately I've been trying to say "no" to more things lately after having said "yes" to everything in the beginning of Whoogle, and now have a ton of features that I speculate are rarely ever used by the community and are not things I want to maintain, but have to now. I've thought about creating an organization, but in the years I've been maintaining the project, nobody has expressed interest in helping me maintain the project except for one person (who then vanished a week later).

My main focus right now is trying to use the little time I dedicate to Whoogle to ensuring core functionality is working and  improving, and leaving nice-to-haves (such as this task) for the future. But I am still somewhat open to it at some point.
